apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
        - name: tea
          image: gcr.io/mineonlium/tea@sha256:5aa028b8dae9d1f1858d2b16fa1b0fd9320f6c34b51c3b31d0727536031ce669
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: tea
  labels:
    app: tea
spec:
  selector:
    app: tea
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
